import { actionCreator } from "./index";

export type ActiveSessionTypes = (
  "BEGIN_SESSION" | "PAUSE_SESSION" |
  "RESUME_SESSION" | "FINISH_SESSION" |
  "QUIT_SESSION" | "ADD_EXERCISE" |
  "CREATE_CUSTOM_EXERCISE" | "LOAD_EXERCISE" |
  "COPY_EXERCISE" | "REMOVE_EXERCISE" |
  "OPEN_EXERCISE" | "CLOSE_EXERCISE" |
  "BEGIN_EXERCISE" | "FINISH EXERCISE"
)

export const activeTypes = {
  BEGIN_SESSION: "BEGIN_SESSION",
  PAUSE_SESSION: "PAUSE_SESSION",
  RESUME_SESSION: "RESUME_SESSION",
  FINISH_SESSION: "FINISH_SESSION",
  QUIT_SESSION: "QUIT_SESSION",
  ADD_EXERCISE: "ADD_EXERCISE",
  CREATE_CUSTOM_EXERCISE: "CREATE_CUSTOM_EXERCISE",
  LOAD_EXERCISE: "LOAD_EXERCISE",
  COPY_EXERCISE: "COPY_EXERCISE",
  REMOVE_EXERCISE: "REMOVE_EXERCISE",
  OPEN_EXERCISE: "OPEN_EXERCISE",
  CLOSE_EXERCISE: "CLOSE_EXERCISE",
  BEGIN_EXERCISE: "BEGIN_EXERCISE",
  FINISH_EXERCISE: "FINISH_EXERCISE"
}

export const activeActions = {
  ADD_EXERCISE: () => actionCreator(activeTypes.ADD_EXERCISE),
  CREATE_CUSTOM_EXERCISE: () => actionCreator(activeTypes.CREATE_CUSTOM_EXERCISE)
}